"""Exact index ledger for the critical Oseen--Volterra obstruction."""

from __future__ import annotations

import json
import math
from fractions import Fraction
from typing import Iterable


def _fraction(value: int | Fraction, name: str) -> Fraction:
    if isinstance(value, bool) or not isinstance(value, (int, Fraction)):
        raise ValueError(f"{name} must be an integer or Fraction")
    return Fraction(value)


def _delta(delta: int | Fraction) -> Fraction:
    value = _fraction(delta, "delta")
    if not Fraction(0) <= value < Fraction(1):
        raise ValueError("delta must lie in [0, 1)")
    return value


def gradient_time_exponent(delta: int | Fraction) -> Fraction:
    """Return p=2+delta from the spacetime gradient gain."""
    return Fraction(2) + _delta(delta)


def sobolev_space_exponent(delta: int | Fraction) -> Fraction:
    """Return q=3p/(3-p) from homogeneous Sobolev in R^3."""
    value = _delta(delta)
    return 3 * (2 + value) / (1 - value)


def serrin_index(delta: int | Fraction) -> Fraction:
    """Return 2/p+3/q for the Sobolev pair generated by grad b."""
    value = _delta(delta)
    return (3 - value) / (2 + value)


def oseen_kernel_exponent(delta: int | Fraction) -> Fraction:
    """Return theta in the same-space differentiated heat-kernel bound."""
    value = _delta(delta)
    return Fraction(3, 2) / (2 + value)


def oseen_time_margin(delta: int | Fraction) -> Fraction:
    """Return 1-theta-1/p, positive exactly when delta>1/2."""
    value = _delta(delta)
    return (2 * value - 1) / (2 * (2 + value))


def packet_gradient_radius_power(delta: int | Fraction) -> Fraction:
    """Return the radius power of one parabolic critical gradient packet."""
    return 1 - 2 * _delta(delta)


def interpolated_serrin_index(
    delta: int | Fraction,
    mixing: int | Fraction,
) -> Fraction:
    """Interpolate the Sobolev pair with L_t^infinity L_x^3."""
    weight = _fraction(mixing, "mixing")
    if not Fraction(0) <= weight <= Fraction(1):
        raise ValueError("mixing must lie in [0, 1]")
    return 1 + weight * (serrin_index(delta) - 1)


def barker_constructed_delta(
    bound: int | Fraction,
    universal_constant: int | Fraction,
) -> Fraction:
    """Return the explicit exponent constructed in Barker's proof."""
    m_value = _fraction(bound, "bound")
    c_value = _fraction(universal_constant, "universal_constant")
    if m_value <= 0 or c_value <= 0:
        raise ValueError("bound and universal_constant must be positive")
    return c_value / (4 * m_value + 2 * c_value)


def barker_serrin_excess(
    bound: int | Fraction,
    universal_constant: int | Fraction,
) -> Fraction:
    """Return (2/p+3/q)-1 for Barker's constructed exponent."""
    m_value = _fraction(bound, "bound")
    c_value = _fraction(universal_constant, "universal_constant")
    if m_value <= 0 or c_value <= 0:
        raise ValueError("bound and universal_constant must be positive")
    return 4 * m_value / (8 * m_value + 5 * c_value)


def barker_oseen_time_margin(
    bound: int | Fraction,
    universal_constant: int | Fraction,
) -> Fraction:
    """Return the exact negative Oseen margin for Barker's exponent."""
    m_value = _fraction(bound, "bound")
    c_value = _fraction(universal_constant, "universal_constant")
    if m_value <= 0 or c_value <= 0:
        raise ValueError("bound and universal_constant must be positive")
    return -2 * m_value / (8 * m_value + 5 * c_value)


def variable_space_margin(
    delta: int | Fraction,
    inverse_input_exponent: int | Fraction,
    inverse_output_exponent: int | Fraction,
) -> Fraction:
    """Return one Oseen time margin when the Lebesgue exponent changes."""
    inverse_in = _fraction(inverse_input_exponent, "inverse_input_exponent")
    inverse_out = _fraction(inverse_output_exponent, "inverse_output_exponent")
    if not Fraction(0) <= inverse_in <= Fraction(1):
        raise ValueError("inverse_input_exponent must lie in [0, 1]")
    if not Fraction(0) <= inverse_out <= Fraction(1):
        raise ValueError("inverse_output_exponent must lie in [0, 1]")
    return oseen_time_margin(delta) - Fraction(3, 2) * (
        inverse_in - inverse_out
    )


def cumulative_variable_space_margin(
    delta: int | Fraction,
    inverse_exponents: Iterable[int | Fraction],
) -> Fraction:
    """Sum the margins along a finite Lebesgue-exponent staircase."""
    values = [_fraction(value, "inverse_exponent") for value in inverse_exponents]
    if len(values) < 2:
        raise ValueError("at least two inverse exponents are required")
    if any(not Fraction(0) <= value <= Fraction(1) for value in values):
        raise ValueError("inverse exponents must lie in [0, 1]")
    return sum(
        (
            variable_space_margin(delta, input_value, output_value)
            for input_value, output_value in zip(values, values[1:])
        ),
        Fraction(0),
    )


def telescoped_variable_space_margin(
    delta: int | Fraction,
    inverse_exponents: Iterable[int | Fraction],
) -> Fraction:
    """Return the closed form of the cumulative staircase margin."""
    values = [_fraction(value, "inverse_exponent") for value in inverse_exponents]
    if len(values) < 2:
        raise ValueError("at least two inverse exponents are required")
    if any(not Fraction(0) <= value <= Fraction(1) for value in values):
        raise ValueError("inverse exponents must lie in [0, 1]")
    steps = len(values) - 1
    return steps * oseen_time_margin(delta) - Fraction(3, 2) * (
        values[0] - values[-1]
    )


def _hardy_parameters(
    gamma: float,
    epsilon: float,
    order: int,
    time: float,
) -> None:
    if not math.isfinite(gamma) or not 0.0 < gamma < 1.0:
        raise ValueError("gamma must lie in (0, 1)")
    if not math.isfinite(epsilon) or epsilon < 0.0:
        raise ValueError("epsilon must be finite and nonnegative")
    if isinstance(order, bool) or not isinstance(order, int) or order < 0:
        raise ValueError("order must be a nonnegative integer")
    if not math.isfinite(time) or time < 0.0:
        raise ValueError("time must be finite and nonnegative")


def hardy_step_ratio(gamma: float, epsilon: float, order: int) -> float:
    """Return the normalised beta factor at a positive iteration order."""
    _hardy_parameters(gamma, epsilon, order, 1.0)
    if order < 1:
        raise ValueError("order must be positive")
    if epsilon == 0.0:
        return 1.0
    x_value = order * epsilon
    return math.exp(
        math.lgamma(1.0 - gamma + x_value)
        - math.lgamma(1.0 + x_value)
        - math.lgamma(1.0 - gamma)
    )


def hardy_iterate_value(
    gamma: float,
    epsilon: float,
    order: int,
    time: float = 1.0,
) -> float:
    """Return H_(gamma,epsilon)^order 1 at one time."""
    _hardy_parameters(gamma, epsilon, order, time)
    if order == 0:
        return 1.0
    if epsilon == 0.0:
        return 1.0
    if time == 0.0:
        return 0.0
    logarithm = order * epsilon * math.log(time)
    logarithm += sum(
        math.log(hardy_step_ratio(gamma, epsilon, step))
        for step in range(1, order + 1)
    )
    return math.exp(logarithm)


def main() -> None:
    barker_bound = Fraction(10)
    barker_constant = Fraction(3)
    payload = {
        "experiment": "critical Oseen--Volterra obstruction",
        "thresholds": {
            str(delta): {
                "p": str(gradient_time_exponent(delta)),
                "q": str(sobolev_space_exponent(delta)),
                "serrin_index": str(serrin_index(delta)),
                "oseen_kernel_exponent": str(oseen_kernel_exponent(delta)),
                "oseen_time_margin": str(oseen_time_margin(delta)),
                "packet_radius_power": str(packet_gradient_radius_power(delta)),
            }
            for delta in (Fraction(0), Fraction(1, 2), Fraction(3, 4))
        },
        "barker_example": {
            "M": str(barker_bound),
            "C5": str(barker_constant),
            "delta": str(
                barker_constructed_delta(barker_bound, barker_constant)
            ),
            "serrin_excess": str(
                barker_serrin_excess(barker_bound, barker_constant)
            ),
            "oseen_time_margin": str(
                barker_oseen_time_margin(barker_bound, barker_constant)
            ),
        },
        "hardy_models": {
            "critical_orders": {
                str(order): hardy_iterate_value(0.4, 0.0, order)
                for order in (1, 4, 16)
            },
            "subcritical_orders": {
                str(order): hardy_iterate_value(0.4, 0.1, order)
                for order in (1, 4, 16)
            },
        },
    }
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
